name: Deploy React App in a single job
on: push
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Gets repository sources
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm run test

      - name: Lint application
        run: npm run lint

      - name: Deploy
        run: echo Deploying…
